### ISSUE TITLE
gitPrivateKey not used to sign commits

### ISSUE THREAD

**Issue by Alexsaphir** [whitesource/renovate-on-prem#228]
Setting up `renovate-on-prem` to sign commit by deploying the helm chart with the following `values.yaml` file:
```yaml
renovate:
  acceptWhiteSourceTos: 'y'
  
  renovatePlatform: 'gitlab'
  renovateEndpoint: 'https://${SECRET_GITLAB_DOMAIN}/api/v4/'
  existingSecret: whitesource-renovate

  config: |
    module.exports = {
      // Enter self-hosted configuration options here.
      // https://docs.renovatebot.com/self-hosted-configuration/
      onboardingConfig: {
        extends: ['config:base',":gitSignOff", ":rebaseStalePrs",":enablePreCommit"],
      },
      gitPrivateKey: '${SECRET_RENOVATE_GIT_PRIVATE_KEY}',
      gitAuthor: '${SECRET_RENOVATE_GIT_AUTHOR}'
    }
```

On gitlab side I enforce the commit signing. All push fails due to the missing signature.
I've made sure that the new line are not interpreted by the yaml using the single quote, when attaching to the pod, `gitPrivateKey` value is a single line still with `\n` characters.

I don't see what more can be done to solve this issue.
